-- ===========================================================================
-- Purple Magic careers. Paste this whole file into the Supabase SQL editor
-- and press Run. Safe to run more than once.
--
-- Project: kvifzyskdmqtmteipvye
-- Generated by careers/build-sql.mjs from careers/jobs.mjs. Do not hand edit.
--
-- HOW IT WORKS
--   The website calls one function, submit_application(). That function scores
--   the answers inside Postgres and writes the row. The answer key lives in a
--   table the public key cannot read, so nobody can look up the right answers,
--   and nobody can read other people's applications.
-- ===========================================================================

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------- 1. table
create table if not exists public.applications (
  id            uuid primary key default gen_random_uuid(),
  created_at    timestamptz not null default now(),
  reference     text not null unique,

  role          text not null,
  role_title    text not null,
  brand         text not null,

  name          text not null,
  phone         text not null,
  email         text not null,

  answers       jsonb not null default '{}'::jsonb,

  auto_score    integer not null default 0,
  max_score     integer not null default 100,
  knockout      boolean not null default false,
  flags         text[]  not null default '{}',

  review_score  integer,
  status        text not null default 'new'
                check (status in ('new','seen','awaiting','task','interview','hired','rejected','call_rejected')),
  notes         text,

  consent_at    timestamptz not null default now(),
  purge_after   date not null default (current_date + interval '12 months'),
  source        text
);

create index if not exists applications_role_idx   on public.applications (role, created_at desc);
create index if not exists applications_score_idx  on public.applications (role, auto_score desc);
create index if not exists applications_status_idx on public.applications (status);

alter table public.applications
  drop constraint if exists applications_one_per_role;
alter table public.applications
  add constraint applications_one_per_role unique (role, email);

-- ------------------------------------------------------------ 2. answer key
create table if not exists public.role_answer_key (
  role       text primary key,
  title      text not null,
  brand      text not null,
  max_points integer not null,
  questions  jsonb not null,
  updated_at timestamptz not null default now()
);

comment on table public.role_answer_key is
  'Points per answer. Never readable by the public key. Regenerate with careers/build-sql.mjs.';

insert into public.role_answer_key (role, title, brand, max_points, questions) values
  ('content-creator-the-lab', 'Content Creator', 'Lab grown diamond brand', 78, '{"q1":{"type":"choice","maxPick":null,"options":{"a":0,"b":4,"c":12,"d":1},"knockouts":[],"flags":{}},"q2":{"type":"choice","maxPick":null,"options":{"a":3,"b":12,"c":5,"d":1},"knockouts":[],"flags":{}},"q3":{"type":"choice","maxPick":null,"options":{"a":3,"b":12,"c":1,"d":5},"knockouts":[],"flags":{}},"q4":{"type":"multi","maxPick":3,"options":{"shoot":4,"oncam":4,"edit":4,"write":4,"photo":3,"ai":3},"knockouts":[],"flags":{}},"q7":{"type":"choice","maxPick":null,"options":{"yes":10,"most":5,"no":0},"knockouts":["no"],"flags":{}},"start":{"type":"choice","maxPick":null,"options":{"now":10,"2w":9,"1m":7,"2m":3},"knockouts":[],"flags":{}},"exp":{"type":"choice","maxPick":null,"options":{"0":4,"1":6,"1-3":10,"3-5":10,"5+":9},"knockouts":[],"flags":{}}}'::jsonb),
  ('customer-relationship-executive', 'Customer Relationship Executive', 'Jewellery showroom, Kokapet', 100, '{"q1":{"type":"multi","maxPick":3,"options":{"te":8,"hi":8,"en":8,"ur":2},"knockouts":[],"flags":{}},"q2":{"type":"choice","maxPick":null,"options":{"a":2,"b":3,"c":12,"d":0},"knockouts":[],"flags":{}},"q3":{"type":"choice","maxPick":null,"options":{"a":3,"b":12,"c":0,"d":2},"knockouts":[],"flags":{}},"q4":{"type":"choice","maxPick":null,"options":{"a":0,"b":12,"c":3,"d":2},"knockouts":[],"flags":{}},"q6":{"type":"choice","maxPick":null,"options":{"yes":10,"most":5,"no":0},"knockouts":["no"],"flags":{}},"q7":{"type":"choice","maxPick":null,"options":{"near":10,"mid":6,"far":2,"move":7},"knockouts":[],"flags":{}},"start":{"type":"choice","maxPick":null,"options":{"now":10,"2w":9,"1m":7,"2m":3},"knockouts":[],"flags":{}},"exp":{"type":"choice","maxPick":null,"options":{"0":4,"1":6,"1-3":10,"3-5":10,"5+":9},"knockouts":[],"flags":{}}}'::jsonb),
  ('graphic-designer-ai', 'Graphic Designer, AI first', 'Jewellery house, Baseerbagh', 72, '{"q1":{"type":"multi","maxPick":4,"options":{"ps":4,"ai":3,"gen":5,"up":4,"fig":2,"ae":3},"knockouts":[],"flags":{}},"q2":{"type":"choice","maxPick":null,"options":{"a":0,"b":12,"c":5,"d":3},"knockouts":[],"flags":{"a":"fidelity"}},"q3":{"type":"choice","maxPick":null,"options":{"a":2,"b":12,"c":3,"d":2},"knockouts":[],"flags":{}},"q4":{"type":"choice","maxPick":null,"options":{"a":4,"b":12,"c":1,"d":0},"knockouts":[],"flags":{}},"start":{"type":"choice","maxPick":null,"options":{"now":10,"2w":9,"1m":7,"2m":3},"knockouts":[],"flags":{}},"exp":{"type":"choice","maxPick":null,"options":{"0":4,"1":6,"1-3":10,"3-5":10,"5+":9},"knockouts":[],"flags":{}}}'::jsonb),
  ('seo-specialist', 'SEO Specialist, AI search', 'Purple Magic', 74, '{"q1":{"type":"choice","maxPick":null,"options":{"a":3,"b":12,"c":0,"d":2},"knockouts":[],"flags":{}},"q2":{"type":"choice","maxPick":null,"options":{"a":2,"b":12,"c":3,"d":1},"knockouts":[],"flags":{}},"q3":{"type":"choice","maxPick":null,"options":{"a":3,"b":12,"c":2,"d":0},"knockouts":[],"flags":{"d":"blackhat"}},"q4":{"type":"multi","maxPick":4,"options":{"gsc":4,"sem":4,"schema":5,"geo":5,"ga":2,"screaming":3},"knockouts":[],"flags":{}},"start":{"type":"choice","maxPick":null,"options":{"now":10,"2w":9,"1m":7,"2m":3},"knockouts":[],"flags":{}},"exp":{"type":"choice","maxPick":null,"options":{"0":4,"1":6,"1-3":10,"3-5":10,"5+":9},"knockouts":[],"flags":{}}}'::jsonb),
  ('video-editor', 'Video Editor', 'Purple Magic', 84, '{"q1":{"type":"choice","maxPick":null,"options":{"a":2,"b":12,"c":0,"d":3},"knockouts":[],"flags":{}},"q2":{"type":"choice","maxPick":null,"options":{"a":2,"b":12,"c":3,"d":5},"knockouts":[],"flags":{}},"q3":{"type":"choice","maxPick":null,"options":{"a":3,"b":12,"c":0,"d":4},"knockouts":[],"flags":{}},"q4":{"type":"multi","maxPick":4,"options":{"ae":6,"ret":5,"cap":3,"snd":4,"thumb":3,"ai":3},"knockouts":[],"flags":{}},"q5":{"type":"choice","maxPick":null,"options":{"yes":10,"maybe":4,"no":0},"knockouts":["no"],"flags":{}},"start":{"type":"choice","maxPick":null,"options":{"now":10,"2w":9,"1m":7,"2m":3},"knockouts":[],"flags":{}},"exp":{"type":"choice","maxPick":null,"options":{"0":4,"1":6,"1-3":10,"3-5":10,"5+":9},"knockouts":[],"flags":{}}}'::jsonb),
  ('inside-sales-the-lab', 'Inside Sales Executive', 'Lab grown diamond brand', 100, '{"q1":{"type":"multi","maxPick":3,"options":{"te":8,"hi":8,"en":6,"ur":2},"knockouts":[],"flags":{}},"q2":{"type":"choice","maxPick":null,"options":{"a":12,"b":6,"c":2,"d":0},"knockouts":[],"flags":{}},"q3":{"type":"choice","maxPick":null,"options":{"a":2,"b":12,"c":3,"d":1},"knockouts":[],"flags":{}},"q4":{"type":"choice","maxPick":null,"options":{"a":0,"b":12,"c":2,"d":4},"knockouts":[],"flags":{}},"q5":{"type":"choice","maxPick":null,"options":{"a":3,"b":12,"c":4,"d":0},"knockouts":[],"flags":{"d":"pushy"}},"q7":{"type":"choice","maxPick":null,"options":{"yes":10,"ok":6,"no":0},"knockouts":["no"],"flags":{}},"start":{"type":"choice","maxPick":null,"options":{"now":10,"2w":9,"1m":7,"2m":3},"knockouts":[],"flags":{}},"exp":{"type":"choice","maxPick":null,"options":{"0":4,"1":6,"1-3":10,"3-5":10,"5+":9},"knockouts":[],"flags":{}}}'::jsonb)
on conflict (role) do update set
  title = excluded.title,
  brand = excluded.brand,
  max_points = excluded.max_points,
  questions = excluded.questions,
  updated_at = now();

-- -------------------------------------------------------------- 3. security
alter table public.applications    enable row level security;
alter table public.role_answer_key enable row level security;

-- No policies on either table, so the anon and authenticated roles can do
-- nothing directly. All access goes through the function below.
revoke all on public.applications    from anon, authenticated;
revoke all on public.role_answer_key from anon, authenticated;

-- -------------------------------------------------------------- 4. scoring
create or replace function public.submit_application(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $fn$
declare
  k            public.role_answer_key%rowtype;
  v_role       text := trim(payload->>'role');
  v_name       text := left(trim(payload->>'name'), 120);
  v_email      text := lower(trim(payload->>'email'));
  v_phone      text := regexp_replace(coalesce(payload->>'phone',''), '[^0-9+]', '', 'g');
  v_answers    jsonb := coalesce(payload->'answers', '{}'::jsonb);
  v_clean      jsonb := '{}'::jsonb;
  qid          text;
  qdef         jsonb;
  ans          jsonb;
  pick         text;
  v_raw        integer := 0;
  v_ko         boolean := false;
  v_flags      text[]  := '{}';
  v_cap        integer;
  v_pts        integer[];
  v_ref        text;
  v_auto       integer;
  akey         text;
  aval         jsonb;
begin
  if v_role is null or v_role = '' then
    raise exception 'role is required' using errcode = '22023';
  end if;

  select * into k from public.role_answer_key where role = v_role;
  if not found then
    raise exception 'unknown role' using errcode = '22023';
  end if;

  if v_name = '' then
    raise exception 'name is required' using errcode = '22023';
  end if;
  if v_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]{2,}$' then
    raise exception 'invalid email' using errcode = '22023';
  end if;
  if v_phone !~ '^(\+?91)?[6-9][0-9]{9}$' then
    raise exception 'invalid phone' using errcode = '22023';
  end if;
  if coalesce((payload->>'consent')::boolean, false) is not true then
    raise exception 'consent is required' using errcode = '22023';
  end if;

  -- Trim what we store so a large paste cannot bloat the row.
  for akey, aval in select * from jsonb_each(v_answers) loop
    if jsonb_typeof(aval) = 'array' then
      v_clean := v_clean || jsonb_build_object(
        akey,
        (select coalesce(jsonb_agg(left(e, 64)), '[]'::jsonb)
           from (select jsonb_array_elements_text(aval) as e limit 10) s)
      );
    else
      v_clean := v_clean || jsonb_build_object(akey, left(aval #>> '{}', 1000));
    end if;
  end loop;

  -- Score the tap answers. Written answers are left for a person to read.
  for qid, qdef in select * from jsonb_each(k.questions) loop
    ans := v_answers -> qid;
    if ans is null then
      continue;
    end if;

    if qdef->>'type' = 'multi' then
      v_cap := coalesce((qdef->>'maxPick')::int, 99);
      v_pts := '{}';
      if jsonb_typeof(ans) = 'array' then
        for pick in select jsonb_array_elements_text(ans) loop
          if qdef->'options' ? pick then
            v_pts := v_pts || (qdef->'options'->>pick)::int;
            if qdef->'knockouts' ? pick then v_ko := true; end if;
            if qdef->'flags' ? pick then
              v_flags := array(select distinct unnest(v_flags || (qdef->'flags'->>pick)));
            end if;
          end if;
        end loop;
        -- Only the best picks count, so extra picks cannot inflate a score.
        v_raw := v_raw + coalesce(
          (select sum(p) from (select unnest(v_pts) as p order by 1 desc limit v_cap) t), 0);
      end if;
    else
      pick := ans #>> '{}';
      if pick is not null and qdef->'options' ? pick then
        v_raw := v_raw + (qdef->'options'->>pick)::int;
        if qdef->'knockouts' ? pick then v_ko := true; end if;
        if qdef->'flags' ? pick then
          v_flags := array(select distinct unnest(v_flags || (qdef->'flags'->>pick)));
        end if;
      end if;
    end if;
  end loop;

  v_auto := greatest(0, least(100,
    case when k.max_points > 0 then round((v_raw::numeric / k.max_points) * 100)::int else 0 end));

  -- Reference the candidate sees. No look alike characters.
  v_ref := 'PM-' || (
    select string_agg(substr('ABCDEFGHJKLMNPQRSTUVWXYZ23456789',
                             1 + floor(random() * 32)::int, 1), '')
    from generate_series(1, 5)
  );

  insert into public.applications
    (reference, role, role_title, brand, name, phone, email, answers,
     auto_score, max_score, knockout, flags, source)
  values
    (v_ref, v_role, k.title, k.brand, v_name, v_phone, v_email, v_clean,
     v_auto, 100, v_ko, v_flags, left(coalesce(payload->>'source',''), 200))
  on conflict (role, email) do update set
    created_at = now(),
    name       = excluded.name,
    phone      = excluded.phone,
    answers    = excluded.answers,
    auto_score = excluded.auto_score,
    knockout   = excluded.knockout,
    flags      = excluded.flags,
    status     = 'new',
    purge_after = current_date + interval '12 months'
  returning reference into v_ref;

  return jsonb_build_object('ok', true, 'reference', v_ref);
end;
$fn$;

-- The public key may call this one function and nothing else.
revoke all on function public.submit_application(jsonb) from public;
grant execute on function public.submit_application(jsonb) to anon, authenticated;

-- ------------------------------------------------------------- 5. shortlist
create or replace view public.application_shortlist as
select
  reference,
  created_at at time zone 'Asia/Kolkata' as applied_ist,
  role_title,
  brand,
  name,
  phone,
  email,
  auto_score,
  review_score,
  knockout,
  flags,
  status,
  answers
from public.applications
where not knockout
order by auto_score desc, created_at asc;

revoke all on public.application_shortlist from anon, authenticated;

-- ------------------------------------------------------------- 6. retention
create or replace function public.purge_old_applications()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare removed integer;
begin
  delete from public.applications where purge_after <= current_date;
  get diagnostics removed = row_count;
  return removed;
end;
$$;

revoke all on function public.purge_old_applications() from public, anon, authenticated;

-- ===========================================================================
-- Done. Check it worked:
--   select role, title, max_points from public.role_answer_key order by role;
--
-- Read applications, strongest first:
--   select * from public.application_shortlist;
-- ===========================================================================
